default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0

development:
  <<: *default
  database: massage_guru_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: massage_guru_test
